Bids inputs
akhanf/snakebids pull request #138
Opened 2022-03-17 02:55 UTC by pvandyken

At long last, I have my major update to `input_generation.py`. The most important change is the new `BidsInputs`, intended to replace the current `dict` returned by `generate_inputs()`. It's API is currently exactly the same as the dict, so to migrate, all that' necessary is to replace calls as such: `inputs['input_lists']` to `inputs.input_lists`. 

By default, `generate_inputs` will still return a dict, and will log a warning saying that the default behaviour will change in an upcoming release. Users can opt-in to the new `BidsInputs` class by setting the `use_bids_inputs` parameter on `generate_inputs()` to `True`, or they can stick with the `dict` and squelch the warning by setting the parameter to `False`.

Most of the functions have been refactored either to simplify them or increase their generality. The details are all written up in my commit messages; refer to them for an orderly account. They are organized and sorted thematically (and all the throw-away commits have been squashed), so it may be easier to review this one commit at a time.

The most important refactor is on the `_process_path_override()`, now called `_parse_custom_path()`, function, which now fully supports filtering using `filter_list()`

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] I have included necessary documentation or comments (as necessary)
- [x] Any dependent changes have been merged and published

2022-03-17 20:48 UTC, tkkuehn reviewed
Looks good to me! The way you structured the commits was indeed helpful for reviewing, and this change introduces a lot of clarity into the API where the original dicts got confusing. A couple of tiny nitpicks that I'm not 100% sure would be functional and aren't really necessary.

The one thing we should consider is how much we want to encourage adoption of the BidsInput class. The warning that existing users are going to be seeing a lot makes the case that users should adopt the new class ASAP, but in that case I think we should transition the template workflow and docs (i.e. the tutorial text, you've included very nice docstrings here) to the new class before merging this.

2022-03-17 20:48 UTC, tkkuehn commented on snakebids/utils/utils.py
> +    match_list = [*match_list]
Could this be `list(match_list)`? That would be a bit more readable imo.

2022-03-17 20:48 UTC, tkkuehn commented on snakebids/core/input_generation.py
> +        bids_tags = read_bids_tags()
I think this could be pulled out of the loop.

2022-03-17 22:00 UTC, pvandyken commented
@tkkuehn, that's a fair point re the warning message on transitioning. I'm happy to comment it out for now, and we can display it when we deem appropriate

2022-05-06 18:08 UTC, pvandyken commented
I've addressed @tkkuehn's comments, and added the docs for the new features.

2022-05-09 18:51 UTC, tkkuehn requested changes
A couple of minor comments on the new documentation, then this is good to go (plus a merge from main).

2022-05-09 18:51 UTC, tkkuehn commented on docs/bids_function/overview.rst
> +            **inputs."subj_wildcards"
The quotes here should be removed.

2022-05-09 18:51 UTC, tkkuehn commented on docs/tutorial/tutorial.md
> +%  Edit: A link would be nice, but pybids docs are abysmal, so there's not much to link to!
Minor: I would tone this down a little in the name of being nice to our fellow open source neuroimaging software developers (even in throwaway comments in our documentation source).

2022-05-09 18:51 UTC, tkkuehn commented on docs/tutorial/tutorial.md
> +The ``filters`` dict is passed directly to the ``get()`` function in ``pybids``, and thus is quite customizable
Nitpick: Add a period to the end of this note.

2022-05-09 18:51 UTC, tkkuehn commented on docs/tutorial/tutorial.md
> +Snakebids is transitioning to a new format for {func}`generate_inputs() <snakebids.generate_inputs()>`. Currently, you need to opt-in to the new features by setting `use_bids_lists=True` in `generate
Nitpick: Add a period on the end.
```suggestion
Snakebids is transitioning to a new format for {func}`generate_inputs() <snakebids.generate_inputs()>`. Currently, you need to opt-in to the new features by setting `use_bids_lists=True` in `generate_inputs()`, but it will become the default in an upcoming version. We recommend all new users opt-in to maintain long term support, so the tuturial is written using the new syntax. A tutorial for the old syntax can be found on [the v0.5.0 docs](https://snakebids.readthedocs.io/en/v0.5.0/tutorial/tutorial.html#part-ii-snakebids).
```

2022-05-09 18:54 UTC, pvandyken commented on docs/tutorial/tutorial.md
> +%  Edit: A link would be nice, but pybids docs are abysmal, so there's not much to link to!
Agreed, thank you for pointing this out

2022-05-09 19:28 UTC, kaitj reviewed
Most of the things I saw when I first glanced through it was fixed. Wasn't sure about a couple of code/text in the steps, but looks good otherwise.

2022-05-09 19:34 UTC, tkkuehn commented
Semi-unrelated to this PR: It doesn't seem like the tests are being run on every commit anymore, and they probably should be.

2022-05-09 20:11 UTC, pvandyken commented
What do you mean by "every" commit? If you push multiple commits at once, it only runs tests on the last commit

2022-05-09 20:18 UTC, tkkuehn commented
As far as I can tell, the only action run for the most recent few commits was the readthedocs build, that's all I really mean.  [658b0d5](https://github.com/akhanf/snakebids/pull/138/commits/658b0d56d77883b91372203398ea3019e0a1fdf9) appears to be the last commit that had the tests run but I'm not sure what the issue is.

2022-05-09 20:21 UTC, pvandyken commented
Ah, I see the problem. But not the reason... very strange

2022-05-09 20:22 UTC, pvandyken commented
Could it possibly relate to the fact that I changed only docs, no code?

2022-05-09 20:57 UTC, kaitj commented
It looks like it is running the tests over on the forked repo. If you look at the most recent actions in @pvandyken's fork, the tests are being run there. It might have been one of the settings that was previously changed, but not sure why it isn't also being run in the main repo.

2022-05-11 14:47 UTC, tkkuehn approved these changes

2022-05-12 13:54 UTC, merged