Update documentation for pybids
akhanf/snakebids pull request #164
Opened 2022-05-13 16:31 UTC by kaitj

## Proposed changes

Adds some documentation for pybids.

- Add docstring to _gen_bids_layout
- Update bids_app/config.rst doc for new pybids variables
- Add instructions to "Running snakebids"

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

2022-05-13 21:33 UTC, pvandyken commented on snakebids/core/input_generation.py
> +    pybids_database_dir : str
These should actually go under the public `generate_inputs()` function. Either copy/paste, or just move

2022-05-13 23:11 UTC, kaitj commented on snakebids/core/input_generation.py
> +    pybids_database_dir : str
Copied over in 17a47f8

2022-05-17 14:30 UTC, pvandyken approved these changes

2022-05-17 15:22 UTC, tkkuehn requested changes
One minor comment otherwise looks good to me!

2022-05-17 19:23 UTC, kaitj commented on docs/running_snakebids/overview.md
> +1. The variables can be updated directly in this file or through the CLI by using `--config pybids_db_dir={path}` to update the database path and `--config pybids_db_reset={True/False}` to indicate w
Fixed in df1fc94.

2022-05-17 19:28 UTC, tkkuehn requested changes

2022-05-17 19:28 UTC, tkkuehn commented on docs/running_snakebids/overview.md
> +1. The variables can be updated directly in this file or through the CLI by using `-pybidsdb-dir {dir}` to update the database path and `--reset-db` to indicate whether the database should be updated
```suggestion
1. The variables can be updated directly in this file or through the CLI by using `-pybidsdb-dir {dir}` to specify the database path and `--reset-db` to indicate that the database should be updated. _Note: CLI arguments take precendence if both CLI and config variables are set._
```
Nitpick to clarify that there doesn't need to be an existing database path to update and that `--reset-db` is a store_true argument.

2022-05-17 20:12 UTC, kaitj commented on docs/running_snakebids/overview.md
> +1. The variables can be updated directly in this file or through the CLI by using `-pybidsdb-dir {dir}` to update the database path and `--reset-db` to indicate whether the database should be updated
Committed suggestions in 7336a1a

2022-05-17 20:13 UTC, tkkuehn approved these changes

2022-05-20 16:11 UTC, merged