BidsInputs Refactoring
akhanf/snakebids pull request #175
Opened 2022-06-15 15:14 UTC by pvandyken

## Proposed changes

Split `BidsInputs` into two classes: a smaller class describing a single dataset component and containing the lists, zip_lists, wildcard dict, and path, and a wrapper class compiling them together that takes the same API as `BidsInputs`. The inner class I've called `BidsComponent` and the wrapper I've called `BidsDataset`. The alternative name for the wrapper was `BidsComponents` (pluralized), but I found it confusing from a documentation perspective, and I think `BidsDataset` is more descriptive.

This new structure cleans up the implementation details in a few ways:

1. The old internal `_BidsLists` named tuple is no longer necessary and has been removed.
2. `input_lists` and `input_wildcards` are now defined in terms of `input_zip_lists`. This will make modification of the dataset (e.g. filtering) much easier, as now only one entry needs to be modified.
3. `BidsComponent` is equipped with an `__eq__()` operator, making testing much easier. Most of the tests in `test_generate_inputs.py` have been modified to take advantage of this new behaviour

Finally, this opens up new ways of interacting with datasets. The previous syntax (e.g. `inputs.input_lists["t1w"]`) will still work, but because `BidsDataset` is implented as a dict, a reverse syntax is also possible (e.g. `inputs["t1w"].input_lists`). This new syntax is possibly more intuitive.

## Backward Compatibility

As `BidsInputs` was always the return of `generate_inputs()` and never intended to be directly accessed, this change should not affect any existing workflows. If anyone feels it necessary, it should be possible to have a stub `BidsInputs` whose `__new__()` returns a copy of `BidsDataset`.

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

2022-06-17 14:30 UTC, tkkuehn requested changes
Overall looks good, just a couple of suggestions.

2022-06-17 14:30 UTC, tkkuehn commented on snakebids/core/input_generation.py
> +    """Component of a BidsDataset mapping entities to their resolved values
It would probably be good to note in the docstring that this is immutable.

2022-06-17 14:30 UTC, tkkuehn commented on snakebids/tests/test_generate_inputs.py
> +    alphabet = st.characters(whitelist_categories=["Ll", "Lu", "Nd"])
I think you can use `BIDS_ALPHABET` here.

2022-06-17 14:30 UTC, tkkuehn commented on snakebids/core/input_generation.py
> +    input_zip_lists: Dict[str, List[str]] = attr.field(on_setattr=attr.setters.frozen)
I think it would be worth adding a validator to make sure that all the zip lists are the same length. Also a validator to make sure the zip lists and input path have the same wildcards.

2022-06-17 14:30 UTC, tkkuehn commented on snakebids/core/input_generation.py
> +        BidsDatasetDic
Typo

2022-06-17 14:51 UTC, pvandyken commented on snakebids/core/input_generation.py
>      Attributes
Hmm good catch... Actually, I think technically `input_lists` and `input_wildcards` should be documented under their respective properties (according to the sphinx docstring standards). I'm never fully sure how to document the attributes/parameters of an attrs class, because they're usually the same thing. My opinion for this is that since this class is not meant to be directly constructed, we should list them as attributes rather than parameters, but it's open to debate

2022-06-17 15:30 UTC, pvandyken commented on snakebids/core/input_generation.py
>      Attributes
Hmm good catch... Actually, I think technically `input_lists` and `input_wildcards` should be documented under their respective properties (according to the sphinx docstring standards). I'm never fully sure how to document the attributes/parameters of an attrs class, because they're usually the same thing. My opinion for this is that since this class is not meant to be directly constructed, we should list them as attributes rather than parameters, but it's open to debate

2022-06-17 15:30 UTC, pvandyken commented on snakebids/core/input_generation.py
>      Attributes
Cool, thanks for the link

2022-06-17 15:40 UTC, pvandyken commented on snakebids/core/input_generation.py
> +    """Component of a BidsDataset mapping entities to their resolved values
Actually, if we wanted full immutability, we could use this [immutabledict](https://github.com/corenting/immutabledict). Do people think it's worth it?

2022-06-17 16:11 UTC, pvandyken commented on snakebids/core/input_generation.py
> +    """Component of a BidsDataset mapping entities to their resolved values
I'm going to branch this into its own issue

2022-06-21 00:25 UTC, pvandyken commented
@tkkuehn I've addressed the comments you left. In addition, I've refactored and organized the testing code, moving all my custom hypothesis strategies to a new module.

2022-07-04 14:59 UTC, tkkuehn approved these changes
A couple of nitpicks that you can address if you agree but I'm otherwise happy with this and don't need to see it again. Thanks again for your work on this, it's really nice!

2022-07-04 14:59 UTC, tkkuehn commented on snakebids/core/input_generation.py
> +        lengths = [len(val) for val in value.values()]
This would be a bit simpler as a set comprehension.

2022-07-04 14:59 UTC, tkkuehn commented on snakebids/core/input_generation.py
> +    def __(self, _, value: Dict[str, List[str]]):
My slight preference would be for this to have an informative name (still prepended with an underscore or two)

2022-07-12 16:18 UTC, pvandyken commented
@akhanf, @kaitj, did you still want to take a look, or should I merge?

2022-07-12 16:40 UTC, kaitj approved these changes

2022-07-12 16:40 UTC, kaitj commented
> 



> @akhanf, @kaitj, did you still want to take a look, or should I merge?

Just took another look at it - looks good to me.

2022-07-13 22:47 UTC, merged