Input aliases
akhanf/snakebids pull request #198
Opened 2022-10-21 22:57 UTC by pvandyken

## Proposed changes

Here we lose the `input_*` portion of the attrs and properties from `BidsComponent` and `BidsDataset`. The original properties are kept as aliases and are documented as such. Thus, this is not a breaking change, however, the shorter names will be preferred going forward. The documentation has thus been completely updated to use the new names. 

A test ensures the aliases are maintaining proper identity.

One "extra" change I made: I noted privately with @akhanf and @kaitj that `BidsComponent.lists` just doesn't seem like a very good name, especially when you consider the equality:

```py
inputs.lists == {
  "bold": {
    "subject": ["001", "002"],
    "session": ["001"],
  }
}
```

The variable definitely doesn't describe a list as such, and is very similar to a Python primitive. We thought we should change the name to `entities`, retiring the existing attribute named `entities` (which was never released in a stable version anyway). This is consistent with the pybids method `get_entities()`, which returns a mapping of entity names to values. Obviously, the old `input_lists` remains the same. Any further feedback on this would be appreciated.

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

2022-10-24 20:09 UTC, kaitj requested changes
Think it looks good for the most part. There were instances where `input_lists` (or `lists`) were still being used rather than `entities`. I've tried to catch as many as I could (left as comments, but will let you determine which ones need to be changed), but may not have caught them all.

2022-10-24 20:09 UTC, kaitj commented on snakebids/core/input_generation.py
>          return {key: value.input_lists for key, value in self.data.items()}
`values.entities`?

2022-10-24 20:09 UTC, kaitj commented on snakebids/core/input_generation.py
> +    @property_alias(entities, "lists", "snakebids.BidsComponent.entities")
"`entities`"? (there is a similar call below)

2022-10-24 20:09 UTC, kaitj commented on snakebids/core/input_generation.py
> +        to their :attr:`lists <snakebids.BidsComponent.entities>`
`entities`

2022-10-24 20:09 UTC, kaitj commented on snakebids/core/input_generation.py
>          return {key: value.input_lists for key, value in self.data.items()}
`value.entities`

2022-10-24 20:09 UTC, kaitj commented on snakebids/core/input_generation.py
> +    def input_lists(self):
`entities`

2022-10-24 20:09 UTC, kaitj commented on snakebids/core/input_generation.py
>          # Add the wildcard item to each output value, using filtering for input_lists
entities

2022-10-24 20:09 UTC, kaitj commented on snakebids/core/input_generation.py
>      #       only been performed on input_lists
entities

2022-10-24 20:09 UTC, kaitj commented on snakebids/tests/test_generate_inputs.py
> +            BidsComponent(name="foo", path=path, zip_lists=zip_lists).input_lists
.entities?

2022-10-25 19:41 UTC, tkkuehn commented
On the naming, I am okay with the naming as implemented in this PR but offer the following comments for thought:

- My only reservation about the name `entities` is that it seems to suggest that it includes every BIDS entity in the matched files, but in fact (I think) only contains the entities that were set as wildcards in `pybids_inputs`. That said, I think the concision is worth the trademark compared to something like `wildcard_entity_values`.
- I don't hate `zip_lists`, but `zippable_entities` or something similar would be clearer at a relatively minor length cost.

2022-10-25 19:55 UTC, akhanf commented
I agree with @pvandyken's 3 points against the name-changing fervour, and if we have a new expand() function then we don't care so much what these are named.. 

I do think the change from input_list to entities is warranted though.. The point @tkkuehn you raise about it not being all the entities could apply to anything in snakebids (since everything is specific to the particular query associated with it), so I'm not too bothered with that..

2022-10-25 20:02 UTC, tkkuehn approved these changes
The code changes seem pretty minimal and correct, and it looks to me like between you and Jason all the docs/comments will be updated appropriately. Thanks!

2022-10-25 20:04 UTC, akhanf approved these changes

2022-10-25 21:51 UTC, pvandyken commented
Okay, hopefully that fixes all the missed references. I'll merge tonight. I wonder if we should have another migration guide before releasing `0.7.0`? It's not likely the aliases will be deprecated any time soon, but maybe it would be helpful...?

2022-10-26 11:58 UTC, kaitj approved these changes

2022-10-26 13:56 UTC, merged