Make some cookiecutter variables optional
akhanf/snakebids pull request #253
Opened 2023-02-21 18:15 UTC by tkkuehn

## Proposed changes

With the note that the project template needs some more attention (we've talked a bit about this -- should it be a functional example app or something more like `poetry create` that just gives you the minimum you need to get going? Probably the latter, but it's currently more like the former.), this resolves #203 to the extent possible while still giving a (semi-)functional setuptools-based package repo.

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] I have included necessary documentation or comments (as necessary)
- [x] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

2023-02-21 18:48 UTC, kaitj approved these changes
Looks good to me

2023-02-21 19:01 UTC, pvandyken requested changes

2023-02-21 19:01 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/setup.py
> +    python_requires=">=3.8",
`snakebids` does still support py37. Do we want to wait until we officially drop, or is there another reason to up the version here?

2023-02-21 19:01 UTC, pvandyken commented on snakebids/project_template/cookiecutter.json
> +  "app_name": "{{ cookiecutter.app_full_name.lower().replace(' ', '_').replace('-', '_') if cookiecutter.app_full_name else 'my_bids_app' }}",
Is it possible to default to the name of the directory the template will be placed in?

2023-02-21 19:08 UTC, kaitj commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
> +    "BIDSVersion": "1.8.0",
Think they mostly just release the docs, but can potentially use this (https://github.com/bids-standard/bids-specification) or their zenodo to grab the latest BIDS version if we do wish to automate this part.

2023-02-21 19:28 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
> +    "BIDSVersion": "1.8.0",
e.g.
```bash
curl https://api.github.com/repos/bids-standard/bids-specification/releases | jq -r '.[0].tag_name' | sed 's/^v//'
```

2023-02-22 15:39 UTC, tkkuehn commented on snakebids/project_template/{{cookiecutter.app_name}}/setup.py
> +    python_requires=">=3.8",
For some reason I thought py37 was EOL and this was outdated. Will remove.

2023-02-22 16:19 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/setup.py
> +    python_requires=">=3.8",
It will be as of July, I was thinking we'd just wait till the bitter end (snakemake is still >=py37

2023-02-22 16:20 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
> +    "BIDSVersion": "1.8.0",
But this would break hard if they had a release with a non-standard tag name. By the time we get something robust, it's probably easier just to keep an eye on the repo and update periodically

2023-02-22 16:55 UTC, tkkuehn commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
> +            "Version": "0.1.0"{{ ',\n            "CodeURL": "http://github.com/cookiecutter.github_username/cookiecutter.app_name"' if cookiecutter.github_username }}{{ ',\n            "Author": "coo
Good catch, fixed

2023-02-22 17:09 UTC, tkkuehn commented on snakebids/project_template/cookiecutter.json
> +  "app_name": "{{ cookiecutter.app_full_name.lower().replace(' ', '_').replace('-', '_') if cookiecutter.app_full_name else 'my_bids_app' }}",
See changes in 571edae

2023-02-22 19:37 UTC, pvandyken requested changes
Just one question on something not changed in the PR, but all of the changes look great!

2023-02-22 19:37 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
>      "Name": "{{cookiecutter.app_name}} - {{cookiecutter.app_description}}",
I know this precedes this PR, but so long as we're reviewing, do we really want the description in the same field as the name?

2023-02-22 21:29 UTC, tkkuehn commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
>      "Name": "{{cookiecutter.app_name}} - {{cookiecutter.app_description}}",
Probably not, good point.

2023-02-22 22:26 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
> +    "Name": "Dataset generated by {{cookiecutter.app_name}}",
Still kind of confused... Why "Dataset generated by..."? What is the purpose of this field? And do we want another "Description" field for app description?

2023-02-23 14:34 UTC, tkkuehn commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
> +    "Name": "Dataset generated by {{cookiecutter.app_name}}",
My current understanding of `pipeline_description.json` is that it's a template for `dataset_description.json` files for datasets generated by the pipeline. Given that we can't know ahead of time what kind of datasets those will be, I think this about the best we can do for a name (but I'm open to suggestions and/or getting rid of the field).

2023-02-23 14:57 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/pipeline_description.json
> +    "Name": "Dataset generated by {{cookiecutter.app_name}}",
Hmmm, I would think more realistically you'd want to merge this `pipeline_description.json` with the `dataset_description.json` from the source dataset? Probably worth meeting to discuss what exactly `pipeline_description.json` should be. If we want to make changes, we can raise a specific PR

2023-02-23 14:57 UTC, pvandyken approved these changes

2023-02-23 15:03 UTC, merged