Bids-validator plugin
akhanf/snakebids pull request #291
Opened 2023-05-09 12:58 UTC by kaitj

## Proposed changes

A second attempt at implementing bids validation (see #222). This time, implementing as a snakebids plugin (resuing some of the code from the previous attempt). The plugin tries to perform validation using the bids-validator unless skipped by the user (`--skip_bids_validation`). If the validation fails, an `InvalidBidsError` is thrown, otherwise validation is performed by default using pybids with a warning informing the user.

As noted in #222:
> Drawing some inspiration from fmriprep, a temporary config file is generated for the system call in (_validate_bids_dir) which includes files to ignore during this validation. Was also wondering if we want to limit the validation to the subject data themselves rather than a full dataset (e.g. ignore participants.tsv, dataset_description.json)?

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] I have included necessary documentation or comments (as necessary)
- [x] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

2023-05-09 13:56 UTC, pvandyken requested changes

2023-05-09 13:56 UTC, pvandyken commented on snakebids/core/input_generation.py
> +def _gen_bids_layout(  # noqa: PLR0913
PLR0913 can be resolved by making the arguments kw-only. I think this is a good approach

2023-05-09 13:56 UTC, pvandyken commented on snakebids/plugins/validate.py
> +class InvalidBidsError(Exception):
It would be nice to have some base snakebids exception to inherit from. Either `SnakebidsException` or `SnakebidsPluginException`?

2023-05-09 13:56 UTC, pvandyken commented on snakebids/plugins/validate.py
> +        self.app = app
The app here should be moved to `__call__`. `__init__` can be used for any user-specified configuration

2023-05-09 13:56 UTC, pvandyken commented on snakebids/plugins/validate.py
> +            self.app.config["bids_validator_success"] = True
Skipping pybids isn't strictly necessary, since pybids doesn't actually do validations (in the latest versions, this is literally true: `validate=True` just causes it to ignore unrecognized files). I also don't know off-hand how pybids handles `.bidsignore` files. If it doesn't read that, keeping pybids validation on is even more important

2023-05-09 13:56 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/config/snakebids.yml
> +    default: False
Can we have `dest: plugins.validator.skip` here. Good to start enforcing namespacing right from the get-go

2023-05-09 13:56 UTC, pvandyken commented on snakebids/plugins/validate.py
> +            self.app.config["bids_validator_success"] = True
Here again, lets use a namespaced location: `plugins.validator.success`. I think just using keys with dots is the way to go here: it accomplishes namespacing just as well as a nested dict, it's shorter to right, and it saves complexity, as we don't need to normalize the `dest` tag from the cli into a nested dict.

2023-05-09 13:56 UTC, pvandyken commented on snakebids/tests/test_validate_plugin.py
> +            "Missing bids-validator installation - falling back to pybids validation."
I think my preference here is to just check if a relevant substring is `in` the warning: enough to make sure we got the right warning message, but not so much that the test immediately breaks if we slightly alter the warning (obviously a total rewrite of the warning will always break the test)

2023-05-09 15:08 UTC, kaitj commented on snakebids/plugins/validate.py
> +        except FileNotFoundError:
This part was borrowed from fmriprep and was tested a couple months ago during the first attempt at implementing the validator. That said, I realized this needs to be slightly modified

2023-05-09 15:08 UTC, kaitj commented on snakebids/core/input_generation.py
> +    validate: bool = True,
Yes, I agree - meant to do this, but forgot to do it before pushing.

2023-05-09 15:25 UTC, kaitj commented on snakebids/plugins/validate.py
> +            self.app.config["bids_validator_success"] = True
From what I could tell from a few threads that are a couple of years old, the `.bidsignore` doesn't do anything in 
pybids. 

Trying to think if there are any situations where pybids validation would fail where we would not want it to and at the moment I can't come up with any. With that in mind, I see no reason not to have pybids validation on. That being said, does setting `validate=True` (e.g. keeping pybids validation on) not conflict with the suggestion below for setting the default to be `validate=False`?

2023-05-09 16:08 UTC, kaitj commented on docs/running_snakebids/overview.md
> +1. The variables can be updated directly in this file or through the CLI by using `--pybidsdb-dir {dir}` to specify the database path and `--reset-db` to indicate that the database should be updated.
Agreed. I think my preference here though might be to update the plugins section of the doc using the validator to: (1) show an updated example of using classes to create plugins and (2) show how to enable the plugin and point users there.

Ultimately, if we have plugins we are creating and distributing with snakebids, is it worth to create a list of available plugins somewhere?

2023-05-09 16:20 UTC, kaitj commented on snakebids/plugins/validate.py
> +class InvalidBidsError(Exception):
Hmm, I like the idea of `SnakebidsPluginException` for something like this, especially if with enabling developers to create their own plugins.

2023-05-09 16:35 UTC, kaitj commented on snakebids/plugins/validate.py
> +            self.app.config["bids_validator_success"] = True
Ahh, I see - had to reread that a couple of times :sweat_smile:. 

So then I think the code currently stands with validate=False throughout should satisfy the first condition. And for the second condition, it would be updating the cookiecutter to:

```py
inputs = generate_inputs(
   ...
   validate=not(config.get("bids_validator_success", False))
```

in which case the pybids validation will be performed regardless of whether the bids-validator can be called so long as the user didn't choose to skip validation.

2023-05-10 10:26 UTC, kaitj commented on docs/running_snakebids/overview.md
> +1. The variables can be updated directly in this file or through the CLI by using `--pybidsdb-dir {dir}` to specify the database path and `--reset-db` to indicate that the database should be updated.
Revamped the plugins part of the docs a little, building off of what Tristan had already started in #261. Split up use and creation of plugins into two sections, and also added a couple notes on recommending namespaced keys for the config and making use of the `SnakebidsPluginError`.

2023-05-10 14:59 UTC, tkkuehn requested changes
Looking good, just a few typos and one suggestion for a potential enhancement to the plugin

2023-05-10 14:59 UTC, tkkuehn commented on docs/bids_app/plugins.md
> +Plugins are a feature in Snakebids that enables you to add custom functionality to your Snakebids application after parsing CLI arguments but before invoking Snakemake. For example, you can use a plu
SnakeBids -> Snakebids

2023-05-10 14:59 UTC, tkkuehn commented on docs/bids_app/plugins.md
> +Plugins are a feature in Snakebids that enables you to add custom functionality to your Snakebids application after parsing CLI arguments but before invoking Snakemake. For example, you can use a plu
"to perform BIDS validation to your SnakeBids app" -> "to perform BIDS validation of your Snakebids app's input"

2023-05-10 14:59 UTC, tkkuehn commented on docs/bids_app/plugins.md
> +--------------
I generally prefer the `##` syntax for subheadings

2023-05-10 14:59 UTC, tkkuehn commented on docs/bids_app/plugins.md
> +To use one or more plugins to your {class}`SnakeBidsApp <snakebids.app.SnakeBidsApp>`, pass them to the {class}`~snakebids.app.SnakeBidsApp` constructor via the {attr}`~snakebids.app.SnakeBidsApp.plu
use -> add

2023-05-10 14:59 UTC, tkkuehn commented on docs/bids_app/plugins.md
> +----------------
`##` syntax?

2023-05-10 14:59 UTC, tkkuehn commented on docs/bids_app/plugins.md
> +As an example, the creation of the bids-validator plugin to run the [BIDS Validator](https://github.com/bids-standard/bids-validator) can be created like so:
Maybe "As an example, a simplified version of the bids-validator plugin that runs the [BIDS Validator] could be defined as follows:"

2023-05-10 14:59 UTC, tkkuehn commented on docs/bids_app/plugins.md
> +A plugin can be used to implement any logic that can be handled by a Python function. In the above example, you may also want to add some logic to check if the BIDS Validator is installed and pass al
Maybe note that prospective users can take a look at the source of the "snakebids.plugins" module for examples?

2023-05-10 14:59 UTC, tkkuehn commented on docs/running_snakebids/overview.md
> +Validation of input BIDS datasets are also enabled by default using the bids-validator plugin. By default, this feature uses the command-line (node.js) version of the [validator](https://www.npmjs.co
"are -> is" in the first sentence

2023-05-10 14:59 UTC, tkkuehn commented on snakebids/plugins/validator.py
> +                raise InvalidBidsError from err
This is optional, but maybe we want to make it configurable whether we raise an exception if the BIDS Validation fails? Catching this error would be kind of a pain (you'd have to do it from `run.py`, and it's possible a user might want to know whether bids validation was successful and change its behaviour accordingly.

2023-05-10 14:59 UTC, tkkuehn commented on snakebids/plugins/validator.py
> +        self.app = app
Is there a reason to assign `self.app` here?

2023-05-10 14:59 UTC, tkkuehn commented on snakebids/project_template/{{cookiecutter.app_name}}/config/snakebids.yml
> + # below are an examples for plugin and custom parameters (e.g. config['smoothing_fwhm'])
"below are an examples" -> "below are examples"

2023-05-10 14:59 UTC, tkkuehn commented on snakebids/tests/test_validate_plugin.py
> +    _logger = logging.getLogger(__name__)
Looks like this might be left over from some debugging?

2023-05-10 15:09 UTC, kaitj commented on snakebids/plugins/validator.py
> +        self.app = app
None in particular other than it was already self assigned before and I just moved the code down rather than search and replace all to just `app`. Can make that change later today though.

2023-05-10 15:11 UTC, kaitj commented on snakebids/tests/test_validate_plugin.py
> +    _logger = logging.getLogger(__name__)
Ahh I have to double check, this was leftover when I was trying to get the warnings to be asserted probably

2023-05-10 15:17 UTC, kaitj commented on docs/bids_app/plugins.md
> +Plugins are a feature in Snakebids that enables you to add custom functionality to your Snakebids application after parsing CLI arguments but before invoking Snakemake. For example, you can use a plu
Is this a change we want to make throughout. It would be inconsistent with the rest of the docs otherwise.

2023-05-10 15:20 UTC, tkkuehn commented on docs/bids_app/plugins.md
> +Plugins are a feature in Snakebids that enables you to add custom functionality to your Snakebids application after parsing CLI arguments but before invoking Snakemake. For example, you can use a plu
I thought the capitalization we typically go with was "Snakebids". A quick look at the docs seems to support that impression

2023-05-10 15:23 UTC, kaitj commented on snakebids/plugins/validator.py
> +                raise InvalidBidsError from err
My initial thought is to leave it as is as I don’t see a situation where the behaviour changes based on validation pass or failure of the input dataset. Open to changing it though.

2023-05-10 15:29 UTC, kaitj commented on docs/bids_app/plugins.md
> +----------------
I think I may leave this as is for now. It would be consistent with some of the other pages and also to leave in the anchors. Does anyone know if the `##` also create anchors?

2023-05-10 15:42 UTC, pvandyken commented on docs/bids_app/plugins.md
> +----------------
The only reason other pages use `---------` is because they used to be in `.rst`. If by anchors, you mean ids you can link to, yes the `##` syntax does make links.

2023-05-10 15:45 UTC, pvandyken commented on snakebids/plugins/validator.py
> +                raise InvalidBidsError from err
Seems easy enough to add a parameter to the `__init__` of the class. Default it to keeping the exception. It adds another condition to test, but if that's not too much hardship, I see no reason not to make this configurable

2023-05-10 19:18 UTC, kaitj commented on snakebids/plugins/validator.py
> +                raise InvalidBidsError from err
Fair enough - easy enough to add a test for this too. I've changed this in the latest commit.

2023-05-12 13:22 UTC, tkkuehn approved these changes
Yeah it is not at all clear to me what's going on with that workflow failure, I think we can probably just merge and address it in a separate PR if it sticks around

2023-05-19 18:34 UTC, kaitj commented
Looks like making a new push fixed that workflow failure.

2023-05-19 22:42 UTC, pvandyken commented
@kaitj, are you still working on this one, or am I good to take another look?

2023-05-19 22:50 UTC, kaitj commented
> @kaitj, are you still working on this one, or am I good to take another look?

Should be good for another look.

2023-06-07 02:59 UTC, pvandyken requested changes
Apologies again for the delay, I left some comments

2023-06-07 02:59 UTC, pvandyken commented on docs/bids_app/plugins.md
> +A plugin is a callable class that accepts a {class}`SnakeBidsApp <snakebids.app.SnakeBidsApp>` as input and returns a modified {class}`SnakeBidsApp` or `None`.
I would clarify `function or callable class`, just for those who aren't as intimate in python and won't realize that those are essentially the same thing

2023-06-07 02:59 UTC, pvandyken commented on docs/bids_app/plugins.md
> +When adding plugin-specific parmaters to the config dictionary, it is recommended to use namespaced keys (e.g. ``plugin.validator.skip``). This will help ensure plugin-specific parameters do not conf
```suggestion
When adding plugin-specific parameters to the config dictionary, it is recommended to use namespaced keys (e.g. ``plugins.validator.skip``). This will help ensure plugin-specific parameters do not conflict with other parameters already defined in the dictionary or by other plugins.
```

2023-06-07 02:59 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/workflow/Snakefile
> +    validate=True if "plugins.validator.success" in config else False,
```suggestion
    validate=config.get("plugins.validator.success", False),
```

2023-06-07 02:59 UTC, pvandyken commented on snakebids/tests/helpers.py
> +    return generate_inputs(root, config, validate=False)
`validate` defaults to `False` already I think? So you don't need this

2023-06-07 02:59 UTC, pvandyken commented on snakebids/tests/test_generate_inputs.py
> +            generate_inputs(root, pybids_inputs, validate=False)
Ditto for all these

2023-06-07 02:59 UTC, pvandyken commented on snakebids/tests/test_validate_plugin.py
> +        mocker.patch("subprocess.check_call", side_effect=FileNotFoundError)
As far as I know, `subprocess.check_call` will never actually raise a `FileNotFoundError`... could you confirm?

2023-06-07 15:41 UTC, kaitj commented on snakebids/tests/test_validate_plugin.py
> +        mocker.patch("subprocess.check_call", side_effect=FileNotFoundError)
> ![image](https://user-images.githubusercontent.com/21226986/238016424-fd9e29ee-5d05-4224-9a7b-c8bf53db4241.png)

From running `subprocess.check_call` manually

2023-06-07 16:36 UTC, pvandyken commented on snakebids/tests/test_validate_plugin.py
> +        mocker.patch("subprocess.check_call", side_effect=FileNotFoundError)
Ah, okay great. Apologies for my doubt, haha

2023-06-07 19:31 UTC, pvandyken requested changes
Sorry for another round of comments, I think I just reviewed this too late last night

2023-06-07 19:31 UTC, pvandyken commented on docs/running_snakebids/overview.md
>  1. Uncomment the lines in `snakebids.yml` containing `pybids_db_dir` and `pybids_db_reset`.
Sorry for missing this last night, but this step should be removed I think, as it's no longer relevant

2023-06-07 19:31 UTC, pvandyken commented on docs/running_snakebids/overview.md
>  1. Uncomment the lines in `snakebids.yml` containing `pybids_db_dir` and `pybids_db_reset`.
And of course, without the first step, probably makes sense to remove step labels and have plain prose

2023-06-07 19:31 UTC, pvandyken commented on docs/running_snakebids/overview.md
> +Validation of input BIDS dataset is also enabled by default using the bids-validator plugin. By default, this feature uses the command-line (node.js) version of the [validator](https://www.npmjs.com/
Enabled by default seems a bit misleading, it's more correct to say the boilerplate app starts with the validator plugin enabled. But without the plugin we don't do any validation

2023-06-07 19:31 UTC, pvandyken commented on snakebids/core/input_generation.py
> +        If False, skips validation of BIDS directory. Otherwise use node.js
The validation done by `generate_inputs` will never touch `node.js`, that's strictly a plugin thing. I'd keep the docstring here focused

2023-06-07 19:31 UTC, pvandyken commented on snakebids/core/input_generation.py
> +        If False, skips validation of BIDS directory. Otherwise use node.js
i.e. the behaviour of this validate doesn't change when the plugin is used, just the way `config['plugins.validate.success']` or whatever changes

2023-06-07 19:31 UTC, pvandyken commented on snakebids/plugins/validator.py
> +                app.config["plugins.validator.success"] = False
A bit confused here because in the boilerplate app, validate is set to the value of this sucess parameter, so if `FileNotFound`, I don't think it's falling back to pybids.

2023-06-07 19:31 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/run.py
> +        plugins=[BidsValidator],
The class needs to be instantiated
```suggestion
        plugins=[BidsValidator()],
```

2023-06-07 19:31 UTC, pvandyken commented on snakebids/plugins/validator.py
> +    Parameters
This docstring belongs under `__call__()`. The main docstring should concern `raise_invalid_bids`

2023-06-07 19:31 UTC, pvandyken commented on snakebids/plugins/validator.py
> +class BidsValidator:
If you're able to, this class could be simplified using attrs

2023-06-08 15:36 UTC, kaitj commented on snakebids/plugins/validator.py
> +                app.config["plugins.validator.success"] = False
I think something like may work?

```
validate=(
    not config.get("plugins.validator.success") and 
    not config.get("plugins.validator.skip")
)
```

| Skip validation _[Config Value]_ | Validator Success _[Config Value]_ | Validate Value |
|-|-|-|
|False _[True]_ | Any _[Any]_ | False |
|True _[False]_ | False _[True]_ | False |
|True _[False]_ | True _[False]_ | True |

2023-06-08 15:55 UTC, pvandyken commented on snakebids/plugins/validator.py
> +                app.config["plugins.validator.success"] = False
The other option is to only link pybids validation to skip. If node validation succeeds, pybids, will succeed for sure. And pybids doesn't strictly validate anyway, it only skips files it doesn't recognize (and that only in the root dataset). So it might even be faster to leave it on.

2023-06-08 16:47 UTC, pvandyken commented on snakebids/plugins/validator.py
> +                app.config["plugins.validator.success"] = False
No real harm in keeping `success`, maybe someone will find it useful. (More likely for detecting validation failures and doing something custom)

There's a possibility enabling validation will make it go faster, because it will retain fewer paths. AFAIK it just looks for a `dataset_description` and checks that paths have valid entitites

2023-06-08 20:01 UTC, kaitj commented on snakebids/plugins/validator.py
> +                app.config["plugins.validator.success"] = False
Latest commit changed the pybids validate logic to only associate with `--skip-bids-validation`. 

I did end up keeping `plugins.validator.success` as you noted. The current use case I can think of is the use of the slightly more complex logic to perform validation with one or the other, but maybe like you said someone else will find it useful for other things.

2023-06-22 16:46 UTC, pvandyken approved these changes
Left one comment RE documentation, but I'd be okay with deferring to a future issue if you'd rather not do it here, I'll leave it up to you

2023-06-22 16:46 UTC, pvandyken commented on snakebids/plugins/validator.py
> +        """Perform BIDS validation of dataset, falling back to the pybids
Looks like this never makes an appearance on the readthedocs reference pages. We should really probably have a new page in addition to 'API' and 'Internals'. If you'd rather just merge this in now, we can make this a new issue.

One thing that might come up though is that I don't know if these dunder methods are currently automatically documented. It might be better to move the bulk of the description to be a class docstring, and keep the `__call__` docstring sparse (sorry that this seems to go against a previous comment... although my previous point about documenting the `app` parameter under `__call__` remains valid). And in this case `raise_invalid_bids` should be documented

2023-06-22 16:46 UTC, pvandyken commented on snakebids/project_template/{{cookiecutter.app_name}}/workflow/Snakefile
> +# If validate success -> False and True -> False
Did you mean to keep this table? I don't really understand it either way

2023-06-22 17:11 UTC, kaitj commented on snakebids/project_template/{{cookiecutter.app_name}}/workflow/Snakefile
> +# If validate success -> False and True -> False
Ahh I did not - that when I was trying to figure out some logic with the previous implementation. Will remove this

2023-06-22 18:16 UTC, kaitj commented on snakebids/plugins/validator.py
> +        """Perform BIDS validation of dataset, falling back to the pybids
I moved some stuff around and agree about the new page, but I think the new page should probably be introduced in a new PR. Feel free to make additional docstring suggestions.

Once thing I noticed (and something to fix in a separate PR), is the docstring styling is inconsistent in the code base.

2023-06-23 12:02 UTC, merged