Update pybids_db parameters
akhanf/snakebids pull request #296
Opened 2023-05-19 10:39 UTC by kaitj

## Proposed changes

Unifies the parameters across the different modules, config, and CLI. The following have been updated:
* References to the pybids database: `pybidsdb_dir`
* References to resetting the database: `pybidsdb_reset`
_(The one caveat to the reset parameter is that `--reset-db` still exists with a deprecation warning. I'm also open to just deprecating this with this PR.)_

Additionally, this PR removes the commented out lines associated with pybidsdb in the config boilerplate in favor of having the user set the parameters via CLI.

Resolves #269 and #270. 

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] I have included necessary documentation or comments (as necessary)
- [x] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

2023-05-19 14:32 UTC, pvandyken requested changes
This is great thanks. It probably is still worth having at least one deprecation cycle for the old `generate_inputs` arguments, just to give people time to transition. Don't document them, and print a warning if they're used, and we'll pull them out next release.

2023-05-19 14:44 UTC, kaitj commented
More of a note to myself since this was more of a global search and replace:

- [ ] remove mention of in commenting of lines in the documentation.

2023-05-19 14:50 UTC, tkkuehn approved these changes
I think a deprecation cycle for `generate_inputs` like Peter said makes sense but have no additional comments, thanks!

2023-05-19 20:04 UTC, tkkuehn approved these changes
One typo to fix but otherwise looks good

2023-05-19 20:04 UTC, tkkuehn commented on snakebids/core/input_generation.py
> +            "deprecated in the next release. To resetset the pybids database, use "
"resetset" -> "reset"

2023-05-19 22:50 UTC, pvandyken requested changes

2023-05-19 22:50 UTC, pvandyken commented on snakebids/core/input_generation.py
> +            "deprecated in the next release. To set the pybids database, use the "
This is pedantic, but I believe it's correct to say it's currently deprecated and will be removed in the next release

2023-05-19 22:50 UTC, pvandyken commented on docs/bids_app/workflow.md
>      derivatives=config.get("derivatives"),
Can we move the old versions to the bottom just in case someone was relying on the order? (But we should really make these arguments kw-only in the future).

2023-05-19 22:50 UTC, pvandyken commented on docs/running_snakebids/overview.md
>  Indexing of large datasets can be a time-consuming process. Snakebids, through `PyBIDS` has the ability to create or leverage an existing database, requiring indexing of datasets to be only performed
The "opt-in" language is maybe a bit confusing? The only sense it's opt-in is that you need to manually connect the config variables to `generate_inputs`. This can probably be cleaned up a bit

2023-05-23 18:02 UTC, kaitj commented on docs/running_snakebids/overview.md
>  Indexing of large datasets can be a time-consuming process. Snakebids, through `PyBIDS` has the ability to create or leverage an existing database, requiring indexing of datasets to be only performed
I tried to reword this part a little bit, but not sure about the "disabled by default". Think we can probably phrase it slightly better.

2023-06-07 03:05 UTC, pvandyken commented on snakebids/cli.py
>          "--reset_db",
Use `help=argparse.SUPPRESS` to hide the old argument from help

2023-06-07 03:07 UTC, pvandyken commented on snakebids/app.py
> +            self.config["pybidsdb_dir"] = args.pybidsdb_dir
I don't think it's a problem if `self.config["pybidsdb_dir"]` is set to `None`? Can we just set it unconditionally?

2023-06-07 03:07 UTC, pvandyken requested changes
Just left a few additional comments, should be good to go after

2023-06-07 19:07 UTC, pvandyken approved these changes

2023-06-07 20:00 UTC, merged