Update README
akhanf/snakebids pull request #298
Opened 2023-05-19 14:10 UTC by kaitj

## Proposed changes

Resolves #96. Quick revamp of the readme and makes references the documentation for more detailed information. Open to suggestions to include more.

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [x] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

2023-05-19 14:41 UTC, pvandyken reviewed
Thanks for tackling this Jason, this is a definite improvement!

I'm fine with leaving `Features` the way it is, we can always let it evolve later, but this is going back conversations we've been happening around how we want to pitch snakebids. A lot of the features listed right now are Snakemake features, and I personally think snakebids has utility to offer beyond its close snakemake integration.

But I think solving this problem will likely involve actually using snakemake in real-life apps outside of snakemake workflows. So I say all this not to propose a change here, but to continue the conversation and keep this thought at the forefront.

2023-05-19 14:41 UTC, pvandyken approved these changes

2023-05-19 14:44 UTC, tkkuehn approved these changes
A couple of minor suggestions to add some more links and clarify our relationship to Snakemake, but otherwise looks good, thanks!

2023-05-19 14:44 UTC, tkkuehn commented on README.md
> +Snakebids is a Python package that facilitates the creation of reproducible and scalable data processing pipelines for neuroimaging data in the BIDS format (e.g. BIDS Apps). It leverages the power of
Maybe `Snakebids is a Python package that extends [Snakemake](https://snakemake.github.io/), allowing users to create reproducible, scalable pipelines for processing neuroimaging data in the [BIDS format](https://bids.neuroimaging.io). Snakebids workflows expose a CLI that conforms to the [BIDS app](https://bids-apps.neuroimaging.io) guidelines.`

2023-05-19 14:44 UTC, tkkuehn commented on README.md
> +## Features
Maybe `All the features of Snakemake, including flexible configuration, parallel execution, and Docker/Singularity support, plus:` then BIDS Compliance, Plugin system, and maybe mention pybids querying somehow?

2023-05-19 14:47 UTC, pvandyken commented on README.md
> +* **BIDS Compliance**: Helper function to ensure BIDS paths adhere to the BIDS specification, promoting data organization and sharing. Additionally, provide command-line invocations of your workflow
One important feature of snakebids is that your app will be able to work on *any* bids dataset, with pretty much any arbitrary level of complexity

2023-05-19 14:51 UTC, pvandyken commented on README.md
> +* **BIDS Compliance**: Helper function to ensure BIDS paths adhere to the BIDS specification, promoting data organization and sharing. Additionally, provide command-line invocations of your workflow
I'd also bring the Bids App closer to the front. Bids Validation seems like a more peripheral feature of snakebids (we don't even do the validation, the user needs the BidsValidator installed on their system)

2023-05-19 14:51 UTC, pvandyken commented on README.md
> +Snakebids is built upon the Snakemake workflow management system and follows the guidelines outlined by the BIDS specification.
I wouldn't state the snakemake acknowledgment too strongly... Actually, I'd like to completely lose our snakemake dependency at some point. I think even `Snakebids builds upon the ...` would soften the tone a bit and be more accurate

2023-05-19 14:54 UTC, kaitj commented on README.md
> +* **BIDS Compliance**: Helper function to ensure BIDS paths adhere to the BIDS specification, promoting data organization and sharing. Additionally, provide command-line invocations of your workflow
Agreed. Couldn’t come up with the right phrasing here - was going for more of a “can generate paths that generally follow the bids spec” rather a validation angle.

2023-05-19 15:02 UTC, pvandyken commented on README.md
> +Snakebids is built upon the Snakemake workflow management system and follows the guidelines outlined by the BIDS specification.
Yeah, that's fine too. I think the current wording just makes it sounds like this a snakemake plugin or something, which isn't really the case (although the only tested use-case right now is more or less as a plugin, but there's nothing intrinsically making this necessary

2023-05-19 15:07 UTC, pvandyken commented on README.md
> +* **BIDS Compliance**: Helper function to ensure BIDS paths adhere to the BIDS specification, promoting data organization and sharing. Additionally, provide command-line invocations of your workflow
Oh I see, I misunderstood what you meant, haha. Mmm, I see. At the risk of being too colloquial, I'm seeing phrases like `Speaks BIDS fluently`, `Easy, flexible construction of valid BIDS paths`, (flexible is important, because pybids has fairly easy bids path construction, but it's not flexible). We also derive output names from an arbitrary set of of input names, automatically managing the identifying information and entities.

But those ideas still have to be molded into a sane prose, haha

2023-05-19 18:47 UTC, kaitj commented on README.md
> +Additionally, Snakebids uses pre-commit hooks (installed via the `poe setup` command above) to lint and format code (we use [black](https://github.com/psf/black), [isort](https://github.com/PyCQA/iso
Added a small note near the top of the contribution section.

2023-05-19 22:56 UTC, pvandyken requested changes
Really like the new Features and Usage section. Thanks!

2023-05-19 22:56 UTC, pvandyken commented on README.md
> +* **BIDS Dataset Compatability**: Seamless workflow functionality with a wide range of BIDS datasets, accomodating various levels of complexity.
Compatability is misspelled, but I think we could use a different word anyway, because BIDS is a first class citizen, not merely compatible. `Works with BIDS`, or something like that maybe?

2023-05-19 22:56 UTC, pvandyken commented on README.md
> +_Note: Snakebids makes use of Poetry's dynamic versioning. To see a version number on locally installed Snakebids versions, you will have to also install dynamic versioning to your poetry installatio
Technically [`poetry-dynamic-versioning`](https://github.com/mtkennerly/poetry-dynamic-versioning), it's a plugin, not native to Poetry

2023-05-19 22:56 UTC, pvandyken commented on README.md
> +Additionally, Snakebids uses pre-commit hooks (installed via the `poe setup` command above) to lint and format code (we use [black](https://github.com/psf/black), [isort](https://github.com/PyCQA/iso
Pylint can be removed

2023-05-19 22:56 UTC, pvandyken commented on README.md
> +Snakebids extends upon the Snakemake workflow management system and follows the guidelines outlined by the BIDS specification.
Snakebids extends ~upon~ the

2023-05-23 13:24 UTC, tkkuehn approved these changes
A couple of nitpicky typos but I don't think I need to see this again once those are fixed. Thanks for taking this on!

2023-05-23 13:24 UTC, tkkuehn commented on README.md
> +Snakebids is a Python package that extends [Snakemake](https://snakemake.github.io), enabling users to create reproducible, scalable pipelines for processing neuroimaging data in the [BIDS format](ht
"Bids App" -> BIDS App

2023-05-23 13:24 UTC, tkkuehn commented on README.md
> +Following installation of Poetry, the development can be setup by running the following commands:
"setup" -> "set up"

2023-05-24 21:05 UTC, pvandyken commented on README.md
> +_Note: Snakebids makes use of Poetry's dynamic versioning. To see a version number on locally installed Snakebids versions, you will have to also install `poetry-dynamic-versioning` plugin to your po
Okay, looks like I made a dumb mistake in the command to add `poetry-dynamic-versioning`. `poetry self add` is not a command

Instead, `pipx inject poetry poetry-dynamic-versioning\[plugin\]`

2023-06-07 02:47 UTC, pvandyken approved these changes
Apologies for delaying my review, I think this is good to go

2023-06-07 14:44 UTC, merged