Test magic args
akhanf/snakebids pull request #305
Opened 2023-06-07 20:40 UTC by tkkuehn

## Proposed changes

Closes #94. The tests aren't super comprehensive but definitely increase the code coverage to the point that they would have caught #287.

2023-06-07 22:54 UTC, pvandyken requested changes
Thanks for implementing the inputs_config strategies, that'll be useful down the road

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/strategies.py
> +def input_config(draw: st.DrawFn) -> InputConfig:
It reads a little weird here, but the convention for strategies is to pluralize the name, so I'd change this to `input_configs`

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/strategies.py
> +    filters = (
Did you have a reason for not using `st.dictionaries` here? It obviously leads to the same outcome, but the native function may have some optimizations (although I'm not sure).

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/strategies.py
> +    wildcard_entities = draw(st.one_of(st.lists(bids_entity()), st.none()))
```suggestion
    wildcard_entities = draw(st.one_of(st.lists(bids_entity()).map(str), st.none()))
```

This will eliminate the need for the below comprehension

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/test_app.py
> +        config_copy["bids_dir"] = "root"  # type: ignore
If you annotate `config_copy` as `dict[str, Any]`, you can eliminate the type ignores

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/strategies.py
> +def inputs_config() -> st.SearchStrategy[InputsConfig]:
As per above, this would be `inputs_configs`

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/test_app.py
> +            for entity in [wildcard.entity for wildcard in wildcards]:
You can do a set subtraction here:
```suggestion
            assert not {wildcard.entity for wildcard in wildcards} - set(inputs_config["bold"].get("wildcards", []))
```
Alternatively a length comparison on the original vs an intersection

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/test_app.py
> +    @given(
You should be able to use your `input_configs` strategy here. Just pull whatever filters, wildcards, and path it gives you

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/test_app.py
> +        st.one_of(
This is more stylistic, but I pretty much always prefer explicit keyword arguments for given. It just makes things clearer and can save headache down the road (test debugging, etc)

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/test_cli.py
> +        p = create_parser()
This is more of a mental note to myself, haha, but I'm assuming the reason mocker works here without you calling `mocker.stopall()` is because you're not using the `spy` method, just `patch`

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/test_cli.py
> +            itertools.chain.from_iterable(
Style point: my convention has been to import `itertools as it`, if you want consistency with the rest of the repo

2023-06-07 22:54 UTC, pvandyken commented on snakebids/tests/test_cli.py
> +            assert isinstance(args.args_dict[f"path_{key_identifier}"], str)
Why do you switch from key access to get?

2023-06-12 20:17 UTC, tkkuehn commented on snakebids/tests/test_app.py
> +            for entity in [wildcard.entity for wildcard in wildcards]:
Going from here, I landed on using the `<=` set operator

2023-06-12 20:19 UTC, tkkuehn commented on snakebids/tests/test_cli.py
> +        p = create_parser()
Ah totally forgot I was supposed to use `mocker.stopall()` generally

2023-06-12 20:21 UTC, tkkuehn commented on snakebids/tests/test_cli.py
> +            assert isinstance(args.args_dict[f"path_{key_identifier}"], str)
No idea, on reflection. I standardized these on key access.

2023-06-12 20:58 UTC, tkkuehn commented
GH actions is being weirdly flaky here but all the tests passed on the last run, so I think this is good for another look

2023-06-13 11:48 UTC, pvandyken commented on snakebids/tests/test_cli.py
> +        p = create_parser()
I don't think it's a huge deal overall, it just took me a couple minutes to make sense of this, so I wanted to make some sort of note, haha

2023-06-13 11:49 UTC, pvandyken commented on snakebids/tests/test_app.py
> +            for entity in [wildcard.entity for wildcard in wildcards]:
Ah, cool. Never realized that was an option

2023-06-13 11:52 UTC, pvandyken commented
Looks like the failures may have to do with the `custom_paths` strategy generating invalid examples. Check out https://pypi.org/project/hypothesis-fspaths/ for generating only valid paths. (I'm not seriously worried about users using null-bytes in their custom_paths, and if they do, that's on them, so I don't think we need to handle it).

2023-06-13 11:55 UTC, pvandyken commented
Ah, sorry, looks like you did take some steps to address the failures. Either way, the library presented is another option (I may incorporate it in the future for other reasons, so we have it on standby at least)

2023-06-13 13:00 UTC, pvandyken approved these changes

2023-06-13 13:23 UTC, merged