Save more provenance information
akhanf/snakebids pull request #308
Opened 2023-06-15 14:37 UTC by tkkuehn

## Proposed changes

Addresses #205 in a reasonably basic way. It's not guaranteed that a Snakebids app even has a version, so this PR just takes a crack at it by assuming the name of the snakemake directory is also the name of an installed package. If anyone has any other ideas, we can straightforwardly add fallback options to `SnakeBidsApp.get_app_version`.

Note that this doesn't do anything about the proposed formatting/comments in the output config. Maybe that would be good to raise as a separate issue.

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] I have included necessary documentation or comments (as necessary)
- [x] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

2023-06-15 15:00 UTC, kaitj commented
Quickly skimmed the review (will do a more thorough look later on), and so far it looks good.

Would there be a situation where the app isn't a distribution package installed in the environment?

2023-06-15 15:05 UTC, tkkuehn commented
> Would there be a situation where the app isn't a distribution package installed in the environment?

An example would be if I find a Snakebids app I want to use on GitHub, clone it, and have Snakebids etc. globally installed in my environment, so I don't bother installing the app to my environment.

A real-world (if kind of weird and likely to change) case is https://github.com/afids/afids-CNN/tree/main/afids_cnn, which wraps a couple of different Snakebids workflows under one package that is not itself a Snakebids workflow.

2023-06-15 15:14 UTC, kaitj commented
Fair enough, then I think one useful thing to add would be a warning that "...the version of the snakebids app cannot be found as it is likely not installed in the environment" or something to that effect, so its not a surprise that the config shows "Unknown" version.

2023-06-20 22:55 UTC, pvandyken commented on snakebids/app.py
> +    def get_app_version(self) -> str | None:
I would set up version as a class attribute and turn this function into a factory. That way a user can easily override with their own version if they prefer. And they can easily access the version later via `app.version` (this will help a version plugin later too)

2023-06-20 23:08 UTC, pvandyken commented on snakebids/app.py
> +        """Attempt to get the app version, returning None if we can't.
If we're moving in this direction, I wonder if we should allow (and encourage) the passing of explicit modules (or string names of modules) to `snakemake_dir` in addition to paths. This would actually simplify the `run.py` file a bit. And this would create some extra liberty e.g. if the snakemake package was in some subpackage `foo.bar`, we'd be able to support that a little better.

2023-06-20 23:08 UTC, pvandyken commented on snakebids/app.py
> +        """Attempt to get the app version, returning None if we can't.
Not necessarily a goal for this PR, but maybe something to think about for the future

2023-06-20 23:13 UTC, pvandyken commented on snakebids/tests/test_app.py
> +                "snakebids_version": "0.0.0",  # poetry-dynamic-versioning
`0.0.0` is only the case if you don't have poetry-dynamic-versioning installed as a plugin (e.g. this test fails on my machine). Off the top of my head I can't think of an "independent" way of getting the snakebids versioning without repeating production code, so as you did with `snakemake_version`, you may be stuck calling `metadata.version("snakebids")` here

2023-06-20 23:16 UTC, pvandyken commented on pyproject.toml
> +importlib_metadata = [ { version = "^6.6.0", python = "<3.8" } ]
In preparation for dropping python37, could you pin this to `==1.4`, which seems to be the version included by default in py38, and make sure everythin works?

2023-06-20 23:18 UTC, pvandyken requested changes
One concern with leaving a warning if no version is found is that if a developer messes up the implementation preventing versioning, users will get that warning and potentially think something is wrong... But then they may still think something is wrong when they read `version=unknown` so maybe it doesn't matter.

2023-06-21 16:02 UTC, tkkuehn commented on snakebids/app.py
> +        """Attempt to get the app version, returning None if we can't.
I didn't address this for now, but is probably worth a separate issue for discussion.

2023-06-21 16:04 UTC, tkkuehn commented
I added a warning where I tried to convey that the missing version will often be nothing for the end user to worry about, but I'm open to changing either or both of the warning's text, and its log level (could make it `INFO`, but those won't usually ever be seen by end users, as discussed in #184 ).

2023-06-28 15:51 UTC, kaitj approved these changes
This lgtm - the warning might be a little long, but I think it conveys what needs to be conveyed and I don't have any other suggestions there.

2023-06-30 02:01 UTC, pvandyken requested changes
Just one comment RE the warning, but once that's resolved no need for re-review

2023-08-04 21:43 UTC, pvandyken commented
@tkkuehn, we had originally said we'd try to get this one in our 0.9 release. Would you still like to? If not, there's no need to maintain py37 support

2023-08-08 14:24 UTC, tkkuehn commented
> We had originally said we'd try to get this one in our 0.9 release. Would you still like to? If not, there's no need to maintain py37 support

I'm open either way, I don't think this is such a major feature that we need to get it in ASAP, and delaying reduces the amount of work to be done to drop py37 I guess

2023-08-08 15:10 UTC, pvandyken commented
How about we just do a race. If the py37 drop is done before this, I'll release without this, otherwise this can go in

2023-08-08 15:23 UTC, pvandyken commented
Nope, looks like just a merge, then you can go ahead

2023-08-08 15:27 UTC, merged