Update dependencies
akhanf/snakebids pull request #322
Opened 2023-08-04 23:37 UTC by pvandyken

This removes any py37 references and:

- Updates all `__position_only` arguments to `position_only, /`
- Refactors code to use `:=` walrus operators where I found that made sense
- Removes any workaround put in previously

Also updated the dependency specs on `numpy` and `scipy`, and removed for pandas. The idea is to restrain to versions where a wheel is available, since numpy and scipy don't maintain wheels for every active python version. Hopefully it doesn't cause any problems

2023-08-08 17:59 UTC, kaitj approved these changes
Overall I think looks good to me. There is the testing time out again (this may be a non issue now, but was there when I first started reviewing) and also have 1 relatively minor comment.

2023-08-08 17:59 UTC, kaitj commented on snakebids/types.py
> +    List,
Can we update the use of `Dict` and `List` to `dict` and `list` or would that break functionality?

2023-08-08 18:13 UTC, pvandyken commented on snakebids/types.py
> +    List,
We need to keep `Dict` around because it's used for subclassing. `List` can go I think

2023-08-10 14:51 UTC, tkkuehn requested changes
Looks good, but needs a merge from main to incorporate the provenance stuff and (maybe?) fix the test failure.

2023-08-10 18:46 UTC, pvandyken commented
The debug statements precommit hook was failing on my machine here with py38 syntax (not sure why, it works elsewhere). Rather than fight it, I just dropped it and activated the debugger checks in ruff, which do the same thing.

2023-08-11 18:59 UTC, tkkuehn approved these changes

2023-08-11 22:01 UTC, merged