Resolve arguments annotated with type: Path
akhanf/snakebids pull request #52
Opened 2021-09-01 18:48 UTC by pvandyken

# Problem
Currently, when supplying arguments to the command line executable (e.g. `run.py`), the `input` and `output` positional arguments are resolved (e.g. `./data` becomes `/home/user/folder/data`) and a new `config.yaml` is generated in the output folder. All keyword arguments (e.g. `--keyword argument`) are printed into the new `config.yaml` as `keyword: argument`. Snakemake is then run using the new config file as config and using the output dir as the working directory. The equivalent snakemake call would be 
```
snakemake --configfile /path/to/output/dir/config/config.yaml --directory /path/to/output/dir
```

Because the working directory is switched, any additional relative paths supplied to the original `run.py` call will now be interpreted relative to the output directory. For instance, if the user had an argument `--supporting-data ./path/to/data`, this path would be evaluated relative to the output folder. Snakemake would search for the data at `/path/to/output/dir/path/to/data`. The user, however, would expect snakemake to look for the folder at a location relative to where `run.py` was called.

# Solution
Argparse allows arguments to be annotated as a specific type such as `str`, `int`, etc. The solution here was to allow users to annotate arguments with either `Path` or `pathlib.Path`. `app.py` will convert these files to `Path`s and resolve them before printing them into the new `config.yaml`. Note that any arguments not annotated with Path will not be affected, even if they look like paths. 

If the solution is green-lit, I can update the documentation to reflect this new behaviour. 

A final side-note, I refactored `app.py` to use the more modern `pathlib` module rather than `os.path`. Should have been its own issue, but it's baked into the code now. Everything's been tested and checks out.

2021-09-02 13:39 UTC, akhanf commented
Thanks Peter! I'll try to take a look at this sometime soon, and I've requested Tristan to do the same when he gets a chance.

2021-09-07 00:53 UTC, akhanf commented on snakebids/app.py
> +import snakemake
any good reason to import the entire snakemake module rather than just the `get_argument_parser` function?

2021-09-07 00:55 UTC, akhanf reviewed
This all looks great to me, but I will let @tkkuehn have a closer look for formatting and the test code.

2021-09-07 16:43 UTC, pvandyken commented on snakebids/app.py
> +import snakemake
That was solely for stylist reasons: it makes it more clear where get_argument_parser comes from. I'm not sure if it introduces a performance cost. If it does, or you just prefer it the old way, it can definitely be reverted.

2021-09-07 16:52 UTC, pvandyken commented
I forgot that my new test code requires pytest-mock. I added it as a dependency into the git workflow.

2021-09-07 17:31 UTC, tkkuehn requested changes
Thanks for the pull request! This fixes an ongoing problem nicely, and I appreciate the included tests.

I have a couple of nitpicky comments but this largely looks good to me.

2021-09-07 17:31 UTC, tkkuehn commented on snakebids/app.py
> +    elif isinstance(path_candidate, os.PathLike):
This can just be an `if` (because the previous `if` statements returns if it triggers.

2021-09-07 17:31 UTC, tkkuehn commented on snakebids/app.py
> +    else:
This `else` can be removed.

2021-09-07 17:31 UTC, tkkuehn commented on snakebids/app.py
> +            if "type" in parse_args and isinstance(parse_args["type"], str):
I think this would be slightly more readable as something like:

```python
if "type" in parse_args:
    try:
        parse_args["type"] = globals()[parse_args["type"]]
    except KeyError as err:
        raise TypeError(
            f"{parse_args['type']} is not available "
            + f"as a type for {name}"
        ) from err
```

2021-09-07 17:31 UTC, tkkuehn commented on snakebids/app.py
> +import snakemake
I don't think there would be a performance cost -- the old way makes it clear what we're using from snakemake, but either way is fine by me.

2021-09-08 04:11 UTC, pvandyken commented on snakebids/app.py
> +Path = pathlib.Path
I typically do the same. My reasoning here was that users could define type in the config as either "Type" or "pathlib.Type". However, this adds very little convenience and probably wouldn't even make it into documentation regardless, so we can definitely do it as you wrote

2021-09-08 04:13 UTC, pvandyken commented
> I don't think there would be a performance cost -- the old way makes it clear what we're using from snakemake, but either way is fine by me.

That's a fair point. I'll let you make the final call on that one

2021-09-08 04:30 UTC, pvandyken commented on snakebids/app.py
> +            if "type" in parse_args and isinstance(parse_args["type"], str):
I'll change it to something like that. I'd still like to check that `"type"` is a `str`, though: I've hit edge cases where `parse_args["type"]` has already been resolved to the class it represents on some previous iteration, but then fails because it's not a string.

2021-09-08 18:39 UTC, tkkuehn commented on snakebids/app.py
> +            if "type" in parse_args and isinstance(parse_args["type"], str):
Sounds good!

2021-09-08 18:46 UTC, tkkuehn commented
> I'll let you make the final call on that one

You can leave it as it is now!

2021-09-08 18:49 UTC, tkkuehn commented on snakebids/app.py
> +Path = pathlib.Path
Ah, I see what you mean -- This way, "Path" and "pathlib,Path" are in `globals()`. With that explanation, this makes sense to me!

2021-09-13 16:38 UTC, akhanf commented
thanks both, looks all good to me now, so will merge this in

2021-09-13 16:38 UTC, merged