Use poetry for dependency management
akhanf/snakebids pull request #60
Opened 2021-11-01 23:57 UTC by pvandyken

This would replace setup.py with a pyproject and use Poetry as a more modern and sustainable approach to dependency management.

Development and test dependencies previously not explicitly required are now listed.

Github workflow is updated to use poetry for publishing and testing. The workflows are based on previous work I did, so they *should* work, but that will need to be tested. I used `secrets.PYPI_API_TOKEN` as on the previous workflow with twine. I assume it's a pypi api key scoped to the snakebids project?

2021-11-02 00:11 UTC, akhanf approved these changes
Thanks, this looks great! 
Look forward to getting a quick demo of setting up poetry on Friday (eg how the .lock file was created).

2021-11-02 00:12 UTC, akhanf commented
Yes, that token is a github secret for this repository, so the CI should work still work -- will see!

2021-11-02 02:24 UTC, pvandyken commented
Once we're ready to merge, I think this should go under 0.4.0-dev. I'm currently wrapping up the basic code for changing output modes (watch for a PR later this week), and once that and everything related is ready, we can push a full 0.4 release?

2021-11-05 13:28 UTC, tkkuehn requested changes
Looks good to me! One small request if there are no objections, but otherwise this looks good to merge.

2021-11-05 13:28 UTC, tkkuehn commented on pyproject.toml
> +pytest-mock = "^3.6.1"
Can we add `pylint = "^2.11.1"` here? I like to use it locally and I don't think poetry has a way to install it separately,

2021-11-05 17:21 UTC, kaitj commented on pyproject.toml
> +pytest-mock = "^3.6.1"
Additionally, for packages using inequality requirements, I think I would lean towards using either caret requirements or multiple requirements so that it doesn't automatically install a different major version that is more likely to introduce changes that aren't backwards compatible (if version in the `.lock` file or the `.lock` file itself isn't found for some reason).

2021-11-05 23:22 UTC, pvandyken commented on pyproject.toml
> +pytest-mock = "^3.6.1"
Sure thing. Actually, it would be good to agree on what code style/quality/linters we'd like to use in the project here-on in + set up appropriate checks in gh-actions. I'll open up a new issue to discuss

2021-11-08 16:43 UTC, pvandyken commented
If it's alright @tkkuehn and @kaitj, can I go ahead and merge this and we'll address the points in a new PR once we get #61 worked out (just because it depends on this commit)

2021-11-09 18:09 UTC, merged